#!/usr/bin/env bash
# This `DEBIAN/postrm` script is run post-uninstallation

set -e

systemctl stop ucpi-node                    || true
systemctl disable ucpi-node                 || true
rm -f /etc/systemd/system/ucpi-node.service || true
systemctl daemon-reload                       || true
