version: '3'

services:
  bootstrap:
    image: enigmampc/ucpi-network-bootstrap-sw:latest
    container_name: bootstrap
    volumes:
      - /tmp/ucpid:/root/.ucpid
      - /tmp/ucpicli:/root/.ucpicli
    stdin_open: true
    tty: true
    environment:
      - http_proxy
      - https_proxy
    expose:
      - 26656
      - 26657

  node:
    image: enigmampc/ucpi-network-node-sw
    depends_on:
      - bootstrap
    volumes:
      - /tmp/ucpid:/tmp/.ucpid
      - /tmp/ucpicli:/root/.ucpicli
    stdin_open: true
    tty: true
    environment:
      - http_proxy
      - https_proxy
