version: '3'

services:
  bootstrap:
    image: enigmampc/ucpi-network-sw-dev-custom-bootstrap:latest
    container_name: bootstrap
    volumes:
#      - /tmp/ucpicli:/root/.ucpicli
      - /tmp/ucpid-bootstrap:/root/.ucpid
#      - /tmp/ucpidbootstrap:/root/.ucpid
      - /tmp/sgx_ucpis:/opt/ucpi/.sgx_ucpis
    stdin_open: true
    tty: true
    environment:
      - http_proxy
      - https_proxy
    expose:
      - 26656
      - 26657
      - 1317
      - 1337
    ports:
      - 26657:26657
      - 26656:26656
      - 1317:1317
      - 1337:1337

#  node:
#    image: enigmampc/ucpi-network-sw-dev-custom-node:latest
#    container_name: node
#    depends_on:
#      - bootstrap
#    volumes:
#      - /tmp/ucpid-bootstrap:/tmp/.ucpid
##      - /tmp/ucpidbootstrap:/tmp/.ucpid
#      - /tmp/ucpid-node:/root/.ucpid
#      - /tmp/ucpicli:/root/.ucpicli
##      - /tmp/sgx_ucpis:/root/.sgx_ucpis
#    stdin_open: true
#    tty: true
#    environment:
#      - http_proxy
#      - https_proxy
#    ports:
#      - 26657:26657
