[package]
name = "enclave_utils"
version = "1.2.4"
authors = ["Cashmaney <itzik@enigma.co>"]
edition = "2018"

[features]
production = []
query-only = []

# This annotation is here to trick the IDE into showing us type information about this crate.
# We always compile to the "sgx" target, so this will always be false.
# when compiling to the "sgx" target, we pull this from the target root with an "extern crate" directive
[target.'cfg(not(target_env = "sgx"))'.dependencies]
sgx_tstd = { branch = "v2.0.0-preview", git = "https://github.com/apache/teaclave-sgx-sdk.git", features = [
  "backtrace"
] }
sgx_types = { branch = "v2.0.0-preview", git = "https://github.com/apache/teaclave-sgx-sdk.git" }

[dependencies]
sgx_trts = { branch = "v2.0.0-preview", git = "https://github.com/apache/teaclave-sgx-sdk.git" }

enclave-ffi-types = { path = "../../ffi-types" }

log = "0.4.14"
lazy_static = "1.4"
